Simplify, move lo accept before invalid drop

diff --git a/templates/iptables-reload b/templates/iptables-reload
--- a/templates/iptables-reload
+++ b/templates/iptables-reload
@@ -2,8 +2,7 @@
 
 CONF=/etc/iptables
 SBIN=/usr/sbin
-UP4="${CONF}/up.ipv4.rules"
-UP6="${CONF}/up.ipv6.rules"
+UP="${CONF}/up.rules.ipv"
 
 . "${CONF}/iptables.conf"
 
@@ -167,104 +166,55 @@ fi
 [[ "${DEBUG}" > 0 ]] && >&2 echo "/sbin/ipset add trusted admin6"
 /sbin/ipset --exist add trusted admin6
 
-# concat ipv4 rules
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules IPv4"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.policy"
-cat "${CONF}/conf.raw.policy" > "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.rules"
-cat "${CONF}/conf.raw.rules" >> "${UP4}"
-echo -ne '\nCOMMIT\n\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.policy"
-cat "${CONF}/conf.nat.policy" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.rules"
-. "${CONF}/conf.nat.rules" >> "${UP4}"
-echo -ne '\nCOMMIT\n\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.policy"
-cat "${CONF}/conf.mangle.policy" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.rules"
-cat "${CONF}/conf.mangle.rules" >> "${UP4}"
-echo -ne '\nCOMMIT\n\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.policy"
-cat "${CONF}/conf.filter.policy" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.conntrack"
-. "${CONF}/conf.filter.rules.head.conntrack" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv4.lo"
-. "${CONF}/conf.filter.rules.head.ipv4.lo" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.lo"
-cat "${CONF}/conf.filter.rules.head.lo" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv4.private"
-. "${CONF}/conf.filter.rules.head.ipv4.private" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv4.icmp"
-. "${CONF}/conf.filter.rules.head.ipv4.icmp" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ratelimit"
-. "${CONF}/conf.filter.rules.head.ratelimit" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.body.ipv4"
-. "${CONF}/conf.filter.rules.body.ipv4" >> "${UP4}"
-echo -ne '\n' >> "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.tail.ipv4"
-. "${CONF}/conf.filter.rules.tail.ipv4" >> "${UP4}"
-echo -ne '\nCOMMIT\n' >> "${UP4}"
-
-# concat ipv6 rules
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules IPv6"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.policy"
-cat "${CONF}/conf.raw.policy" > "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.rules"
-cat "${CONF}/conf.raw.rules" >> "${UP6}"
-echo -ne '\nCOMMIT\n\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.policy"
-cat "${CONF}/conf.nat.policy" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.rules"
-. "${CONF}/conf.nat.rules" >> "${UP6}"
-echo -ne '\nCOMMIT\n\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.policy"
-cat "${CONF}/conf.mangle.policy" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.rules"
-cat "${CONF}/conf.mangle.rules" >> "${UP6}"
-echo -ne '\nCOMMIT\n\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.policy"
-cat "${CONF}/conf.filter.policy" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.conntrack"
-. "${CONF}/conf.filter.rules.head.conntrack" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv6.lo"
-. "${CONF}/conf.filter.rules.head.ipv6.lo" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.lo"
-cat "${CONF}/conf.filter.rules.head.lo" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv6.private"
-. "${CONF}/conf.filter.rules.head.ipv6.private" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ipv6.icmp"
-. "${CONF}/conf.filter.rules.head.ipv6.icmp" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ratelimit"
-. "${CONF}/conf.filter.rules.head.ratelimit" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.body.ipv6"
-. "${CONF}/conf.filter.rules.body.ipv6" >> "${UP6}"
-echo -ne '\n' >> "${UP6}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.tail.ipv6"
-. "${CONF}/conf.filter.rules.tail.ipv6" >> "${UP6}"
-echo -ne '\nCOMMIT\n' >> "${UP6}"
+for V in 4 6; do
+  # concat rules
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules IPv${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.policy"
+  cat "${CONF}/conf.raw.policy" > "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.raw.rules"
+  cat "${CONF}/conf.raw.rules" >> "${UP}${V}"
+  echo -ne '\nCOMMIT\n\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.policy"
+  cat "${CONF}/conf.nat.policy" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.nat.rules"
+  . "${CONF}/conf.nat.rules" >> "${UP}${V}"
+  echo -ne '\nCOMMIT\n\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.policy"
+  cat "${CONF}/conf.mangle.policy" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.mangle.rules"
+  cat "${CONF}/conf.mangle.rules" >> "${UP}${V}"
+  echo -ne '\nCOMMIT\n\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.policy"
+  cat "${CONF}/conf.filter.policy" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.accept"
+  . "${CONF}/conf.filter.rules.head.accept" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.invalid"
+  . "${CONF}/conf.filter.rules.head.invalid" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.private"
+  . "${CONF}/conf.filter.rules.head.private" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.icmp"
+  . "${CONF}/conf.filter.rules.head.icmp" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.head.ratelimit"
+  . "${CONF}/conf.filter.rules.head.ratelimit" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.body.ipv${V}"
+  . "${CONF}/conf.filter.rules.body.ipv${V}" >> "${UP}${V}"
+  echo -ne '\n' >> "${UP}${V}"
+  [[ "${DEBUG}" > 0 ]] && >&2 echo "generate rules conf.filter.rules.tail"
+  . "${CONF}/conf.filter.rules.tail" >> "${UP}${V}"
+  echo -ne '\nCOMMIT\n' >> "${UP}${V}"
+done
 
 # restore rules
-[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv4 rules: ${UP4}"
-/sbin/iptables-restore < "${UP4}"
-[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv6 rules: ${UP6}"
-/sbin/ip6tables-restore < "${UP6}"
+[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv4 rules: ${UP}4"
+/sbin/iptables-restore < "${UP}4"
+[[ "${DEBUG}" > 0 ]] && >&2 echo "load ipv6 rules: ${UP}6"
+/sbin/ip6tables-restore < "${UP}6"
